# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#_config.yml
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Normie Woman Ring
email: zucch1n1@posteo.net
description: >- # this means to ignore newlines until "baseurl:"
  A webring for all normie women
url: https://beefsteaktomatoes.github.io

# Build settings
markdown: kramdown
# theme: minima
# plugins:
#   - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

collections:
  websites:
    output: true
    permalink: /sites/:name

defaults:
  -
    scope:
      path: ""
      type: "websites"
    values:
      layout: site_html

# Webring contribution

repository: https://github.com/beefsteaktomatoes/normie-woman-ring
new_site_url: https://github.com/beefsteaktomatoes/normie-woman-ring/new/master/_websites
